### ISSUE TITLE
Go live App Store / Play Store

### ISSUE THREAD

**Issue by patricebender** [GitP4tt/letsGetTogether#10]
- [ ] #9 New, simpler entry screen
- [ ] #11 Rename the application
- [ ] #15 More cards
- [ ] #17 Chose-Who-Drinks
- [ ] #14 Splash Screen
- [ ] #13 Center Toasts
- [ ] #20 Design a Logo
- [ ] #18 Profile picture from camera / camera roll
